import 'package:flutter/material.dart';

import 'app_palette.dart';

/// Presentation metadata for technologies, document types and course levels.
///
/// Iconography is vector-only (Material Symbols) — never emoji, which is
/// font-dependent and cannot be themed or sized consistently.
abstract final class TechPalette {
  static const Map<String, Color> _colors = <String, Color>{
    'azure': Color(0xFF0089D6),
    'microsoft azure': Color(0xFF0089D6),
    'azure devops': Color(0xFF0078D4),
    'gcp': Color(0xFF4285F4),
    'google cloud': Color(0xFF4285F4),
    'terraform': Color(0xFF844FBA),
    'iac': Color(0xFF844FBA),
    'devops': Color(0xFF00C7B7),
    'ci/cd': Color(0xFF00C7B7),
    'cloud': Color(0xFF0288D1),
    'linux': Color(0xFFFCC624),
    'bash': Color(0xFF4EAA25),
    'system design': Color(0xFFFFB300),
    'architecture': Color(0xFFFFB300),
    'python': AppPalette.darkBrandGlow,
    'react': AppPalette.darkInfo,
    'next.js': AppPalette.darkInfo,
    'node.js': AppPalette.darkGreen,
    'express': AppPalette.darkGreen,
    'angular': AppPalette.darkDanger,
    'fastapi': AppPalette.darkGreenSoft,
    'docker': AppPalette.darkBrandGlow,
    'kubernetes': AppPalette.darkBrandGlow,
    'go': AppPalette.darkInfo,
    'golang': AppPalette.darkInfo,
    'rust': AppPalette.darkAccent,
    'kafka': AppPalette.darkViolet,
    'cybersecurity': AppPalette.darkViolet,
    'security': AppPalette.darkViolet,
    'flutter': Color(0xFF54C5F8),
    'aws': Color(0xFFFF9900),
    'postgresql': AppPalette.darkBrandGlow,
    'generative ai': AppPalette.darkViolet,
    'ai & machine learning': AppPalette.darkViolet,
    'typescript': Color(0xFF3178C6),
    'javascript': Color(0xFFF7DF1E),
    'data structures': Color(0xFF8E44AD),
    'algorithms': Color(0xFF8E44AD),
    'java': Color(0xFFED8B00),
    'spring boot': Color(0xFF6DB33F),
    'c++': Color(0xFF00599C),
    'microservices': Color(0xFF00B4D8),
    'data engineering': Color(0xFF0288D1),
    'analytics': Color(0xFF4285F4),
    'vue': Color(0xFF42B883),
    'pinia': Color(0xFFFFD859),
    'django': Color(0xFF092E20),
    'react native': Color(0xFF61DAFB),
    'c#': Color(0xFF512BD4),
    'csharp': Color(0xFF512BD4),
    '.net': Color(0xFF512BD4),
    'dotnet': Color(0xFF512BD4),
    'c# / .net': Color(0xFF512BD4),
    'kotlin': Color(0xFF7F52FF),
    'android': Color(0xFF3DDC84),
    'android / kotlin': Color(0xFF7F52FF),
    'swift': Color(0xFFF05138),
    'ios': Color(0xFFF05138),
    'swiftui': Color(0xFFF05138),
    'ios / swift': Color(0xFFF05138),
    'php': Color(0xFF777BB4),
    'laravel': Color(0xFFFF2D20),
    'php & laravel': Color(0xFFFF2D20),
    'mongodb': Color(0xFF47A248),
    'nosql': Color(0xFF47A248),
    'redis': Color(0xFFDC382D),
    'graphql': Color(0xFFE10098),
    'git': Color(0xFFF05032),
    'github': Color(0xFFF05032),
    'git & github': Color(0xFFF05032),
    'ethical hacking': Color(0xFF00E676),
    'kali linux': Color(0xFF00E676),
    'sql': Color(0xFF4479A1),
    'mysql': Color(0xFF4479A1),
    'html': Color(0xFFE34F26),
    'html5': Color(0xFFE34F26),
    'css': Color(0xFF1572B6),
    'css3': Color(0xFF1572B6),
    'spring': Color(0xFF6DB33F),
  };

  static const Map<String, IconData> _icons = <String, IconData>{
    'azure': Icons.cloud_circle_rounded,
    'microsoft azure': Icons.cloud_circle_rounded,
    'azure devops': Icons.all_inclusive_rounded,
    'gcp': Icons.cloud_sync_rounded,
    'google cloud': Icons.cloud_sync_rounded,
    'terraform': Icons.layers_rounded,
    'iac': Icons.layers_rounded,
    'devops': Icons.all_inclusive_rounded,
    'ci/cd': Icons.published_with_changes_rounded,
    'cloud': Icons.cloud_rounded,
    'linux': Icons.terminal_rounded,
    'bash': Icons.code_rounded,
    'system design': Icons.architecture_rounded,
    'architecture': Icons.account_tree_rounded,
    'python': Icons.code_rounded,
    'react': Icons.widgets_rounded,
    'next.js': Icons.widgets_rounded,
    'node.js': Icons.hub_rounded,
    'express': Icons.hub_rounded,
    'angular': Icons.change_history_rounded,
    'fastapi': Icons.bolt_rounded,
    'docker': Icons.inventory_2_rounded,
    'kubernetes': Icons.hub_rounded,
    'go': Icons.rocket_launch_rounded,
    'golang': Icons.rocket_launch_rounded,
    'rust': Icons.settings_rounded,
    'kafka': Icons.swap_horiz_rounded,
    'cybersecurity': Icons.shield_rounded,
    'security': Icons.shield_rounded,
    'flutter': Icons.phone_iphone_rounded,
    'aws': Icons.cloud_rounded,
    'postgresql': Icons.storage_rounded,
    'generative ai': Icons.auto_awesome_rounded,
    'ai & machine learning': Icons.auto_awesome_rounded,
    'typescript': Icons.integration_instructions_rounded,
    'javascript': Icons.javascript_rounded,
    'data structures': Icons.account_tree_rounded,
    'algorithms': Icons.scatter_plot_rounded,
    'java': Icons.coffee_rounded,
    'spring boot': Icons.eco_rounded,
    'spring': Icons.eco_rounded,
    'c++': Icons.memory_rounded,
    'microservices': Icons.scatter_plot_rounded,
    'data engineering': Icons.analytics_rounded,
    'analytics': Icons.analytics_rounded,
    'vue': Icons.splitscreen_rounded,
    'pinia': Icons.grain_rounded,
    'django': Icons.dns_rounded,
    'react native': Icons.stay_current_portrait_rounded,
    'c#': Icons.developer_mode_rounded,
    'csharp': Icons.developer_mode_rounded,
    '.net': Icons.developer_mode_rounded,
    'dotnet': Icons.developer_mode_rounded,
    'c# / .net': Icons.developer_mode_rounded,
    'kotlin': Icons.android_rounded,
    'android': Icons.android_rounded,
    'android / kotlin': Icons.android_rounded,
    'swift': Icons.phone_iphone_rounded,
    'ios': Icons.phone_iphone_rounded,
    'swiftui': Icons.phone_iphone_rounded,
    'ios / swift': Icons.phone_iphone_rounded,
    'php': Icons.web_rounded,
    'laravel': Icons.web_rounded,
    'php & laravel': Icons.web_rounded,
    'mongodb': Icons.storage_rounded,
    'nosql': Icons.storage_rounded,
    'redis': Icons.flash_on_rounded,
    'graphql': Icons.hub_rounded,
    'git': Icons.fork_right_rounded,
    'github': Icons.fork_right_rounded,
    'git & github': Icons.fork_right_rounded,
    'ethical hacking': Icons.security_rounded,
    'kali linux': Icons.security_rounded,
    'sql': Icons.table_chart_rounded,
    'mysql': Icons.table_chart_rounded,
    'html': Icons.language_rounded,
    'html5': Icons.language_rounded,
    'css': Icons.brush_rounded,
    'css3': Icons.brush_rounded,
  };

  static Color colorFor(String tech) =>
      _colors[tech.trim().toLowerCase()] ?? AppPalette.darkBrandGlow;

  static IconData iconFor(String tech) =>
      _icons[tech.trim().toLowerCase()] ?? Icons.terminal_rounded;

  static Color levelColor(String level) => switch (level.trim().toLowerCase()) {
        'beginner' => AppPalette.darkBrandGlow,
        'intermediate' => AppPalette.darkGreen,
        'advanced' => AppPalette.darkViolet,
        'architect' || 'expert' => AppPalette.darkAccent,
        _ => AppPalette.darkGreen,
      };
}

/// Presentation metadata for course resource documents.
abstract final class DocPalette {
  static IconData iconFor(String type) => switch (type.trim().toLowerCase()) {
        'pdf' || 'book' || 'paper' => Icons.picture_as_pdf_rounded,
        'code' || 'lab' || 'notebook' => Icons.code_rounded,
        'cheatsheet' || 'cheat sheet' || 'sheet' => Icons.description_rounded,
        'slides' || 'deck' => Icons.slideshow_rounded,
        'video' => Icons.play_circle_fill_rounded,
        'link' || 'url' => Icons.link_rounded,
        _ => Icons.insert_drive_file_rounded,
      };

  static Color colorFor(String type) => switch (type.trim().toLowerCase()) {
        'pdf' || 'book' || 'paper' => AppPalette.darkDanger,
        'code' || 'lab' || 'notebook' => AppPalette.darkInfo,
        'cheatsheet' || 'cheat sheet' || 'sheet' => AppPalette.darkAccent,
        'slides' || 'deck' => AppPalette.darkViolet,
        'video' => AppPalette.darkBrandGlow,
        'link' || 'url' => AppPalette.darkGreenSoft,
        _ => AppPalette.darkTextSecondary,
      };

  static String labelFor(String type) => switch (type.trim().toLowerCase()) {
        'pdf' || 'book' || 'paper' => 'PDF',
        'code' || 'lab' || 'notebook' => 'Code',
        'cheatsheet' || 'cheat sheet' || 'sheet' => 'Cheatsheet',
        'slides' || 'deck' => 'Slides',
        'video' => 'Video',
        'link' || 'url' => 'Link',
        _ => 'Resource',
      };
}
